const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const store={get(k,d=null){try{const v=localStorage.getItem(k);return v===null?d:JSON.parse(v)}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const FALLBACK=[
  {id:153312,media_type:"tv",title:"Solo Leveling",overview:"Sung Jin-Woo ganha uma nova habilidade que permite evoluir sem limites.",poster_path:null,backdrop_path:null,vote_average:8.7},
  {id:37854,media_type:"tv",title:"One Piece",overview:"A aventura de Luffy e sua tripulação em busca do lendário One Piece.",poster_path:null,backdrop_path:null,vote_average:8.7},
  {id:85937,media_type:"tv",title:"Demon Slayer",overview:"Tanjiro inicia sua jornada para salvar sua irmã e enfrentar demônios.",poster_path:null,backdrop_path:null,vote_average:8.6},
  {id:95479,media_type:"tv",title:"Jujutsu Kaisen",overview:"Yuji Itadori entra no mundo dos feiticeiros para combater maldições.",poster_path:null,backdrop_path:null,vote_average:8.5}
];
const avatars=["https://i.pravatar.cc/160?img=12","https://i.pravatar.cc/160?img=5","https://i.pravatar.cc/160?img=11","https://i.pravatar.cc/160?img=32","https://i.pravatar.cc/160?img=44","https://i.pravatar.cc/160?img=47","https://i.pravatar.cc/160?img=49","https://i.pravatar.cc/160?img=52","https://i.pravatar.cc/160?img=58","https://i.pravatar.cc/160?img=60"];
const localGenres=["Ação","Aventura","Comédia","Drama","Fantasia","Romance","Terror","Mistério","Sobrenatural","Esporte","Isekai","Escolar"];
let state={page:location.hash.slice(1)||"home",user:store.get("ad_user"),list:store.get("ad_list",[]),history:store.get("ad_history",[]),avatar:store.get("ad_avatar",avatars[0]),search:"",home:null,details:null};

function toast(msg,type="ok"){const d=document.createElement("div");d.className=`toast ${type}`;d.textContent=msg;$("#toast-root").append(d);setTimeout(()=>d.remove(),3200)}
function esc(x=""){return String(x).replace(/[&<>"\']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;",'\'':"&#039;"}[m]))}
function img(path,size="w500"){return path?`https://image.tmdb.org/t/p/${size}${path}`:"/assets/animedragon-dragon.png"}
function year(x){return String(x?.first_air_date||x?.release_date||"").slice(0,4)||"—"}
function nav(page){location.hash=page}
window.addEventListener("hashchange",()=>{state.page=location.hash.slice(1)||"home";render()});

function layout(inner){
 const navs=[["home","⌂","Início"],["anime","◈","Animes"],["films","▣","Filmes"],["genres","✦","Gêneros"],["calendar","▦","Calendário"],["list","♡","Minha Lista"],["history","◷","Histórico"],["profile","◉","Perfil"]];
 return `<div class="shell"><aside class="sidebar"><div class="brand"><img src="/assets/animedragon-dragon.png"><div><strong>AnimeDragon</strong><small>Ultra Remastered</small></div></div><div class="nav-title">Explorar</div><nav class="nav">${navs.map(n=>`<button class="${state.page===n[0]?"active":""}" data-nav="${n[0]}"><i class="ico">${n[1]}</i><span>${n[2]}</span></button>`).join("")}</nav><div class="nav-title">Sistema</div><nav class="nav"><button data-nav="settings"><i class="ico">⚙</i><span>Configurações</span></button><button data-nav="notifications"><i class="ico">♢</i><span>Notificações</span></button></nav><div class="sidebar-bottom"><div class="account-mini">${userMini()}</div><nav class="nav"><button id="logout"><i class="ico">⇥</i><span>Sair</span></button></nav></div></aside><main class="main"><header class="topbar"><div class="search"><span>⌕</span><input id="global-search" placeholder="Buscar animes, filmes, gêneros..." value="${esc(state.search)}"></div><div class="top-actions"><button class="icon-btn" data-nav="notifications">♧</button><button class="icon-btn" id="theme">☾</button><button class="profile-chip" data-nav="profile"><img class="avatar" src="${esc(state.avatar)}"><div><b>${esc(state.user?.name||"Visitante")}</b><small>${state.user?"Conta AnimeDragon":"Conta demo"}</small></div></button></div></header><div class="content">${inner}</div><div class="mobile-nav">${navs.slice(0,5).map(n=>`<button class="${state.page===n[0]?"active":""}" data-nav="${n[0]}"><b>${n[1]}</b>${n[2]}</button>`).join("")}</div></main></div>`;
}
function userMini(){return state.user?`<div class="user-row"><img class="avatar" src="${esc(state.avatar)}"><div><b>${esc(state.user.name)}</b><small>${esc(state.user.email||"")}</small></div></div>`:`<button class="primary" style="width:100%;padding:9px" id="login-open">Entrar / Criar conta</button>`}
function section(title,content){return `<section class="section"><div class="section-head"><h2>${title}</h2></div>${content}</section>`}
function card(p){return `<article class="card" data-id="${p.id}" data-type="${p.media_type||"tv"}"><img class="poster" src="${img(p.poster_path)}" loading="lazy" alt="${esc(p.title)}"><div class="card-body"><div class="card-title">${esc(p.title)}</div><div class="card-sub">${year(p)} • ${p.media_type==="movie"?"Filme":"Anime/Série"}</div><div class="card-meta"><span class="rating">★ ${Number(p.vote_average||0).toFixed(1)}</span><span>${p.media_type==="movie"?"FILME":"TV"}</span></div></div></article>`}
function cards(items=[]){return `<div class="cards">${items.map(card).join("")}</div>`}
function skeletons(n=6){return `<div class="cards">${Array.from({length:n},()=>`<div class="card"><div class="poster" style="background:linear-gradient(110deg,#06172d,#0b2948,#06172d);animation:pulse 1.3s infinite"></div><div class="card-body"><div style="height:12px;background:#0b2948;border-radius:5px"></div><div style="height:8px;background:#0a223b;border-radius:5px;margin-top:8px;width:65%"></div></div></div>`).join("")}</div>`}

async function api(path){const r=await fetch(path);const d=await r.json().catch(()=>({ok:false,error:"Resposta inválida"}));if(!r.ok||d.ok===false)throw new Error(d.error||`HTTP ${r.status}`);return d}
async function loadHome(){if(state.home)return state.home;try{state.home=await api("/api/tmdb/home")}catch(e){state.home={ok:false,trending:FALLBACK,anime:FALLBACK,movies:[],top:FALLBACK,error:e.message}}return state.home}

function home(){const d=state.home;const all=d?.trending?.length?d.trending:FALLBACK;const hero=all[0]||FALLBACK[0];return `<div class="layout"><div><section class="hero" style="${hero.backdrop_path?`background-image:linear-gradient(90deg,#03101e 0%,rgba(3,14,28,.9) 34%,rgba(3,14,28,.2) 72%,rgba(3,14,28,.5)),url('${img(hero.backdrop_path,"w1280")}')`:""}"><div class="hero-content"><span class="badge">TMDB • EM DESTAQUE</span><h1>${esc(hero.title)}</h1><p>${esc(hero.overview||"Catálogo sincronizado automaticamente pelo TMDB.")}</p><div class="meta"><span class="rating">★ ${Number(hero.vote_average||0).toFixed(1)}/10</span><span>${year(hero)}</span><span>${hero.media_type==="movie"?"Filme":"Anime / Série"}</span></div><div class="actions"><button class="primary" data-id="${hero.id}" data-type="${hero.media_type}">▶ Ver detalhes</button><button class="secondary" data-list-title="${esc(hero.title)}">＋ Minha Lista</button></div></div></section>${section("🔥 Em Alta",cards(all.slice(0,10)))}${section("⚡ Animes populares",cards((d?.anime||FALLBACK).slice(0,10)))}${section("🎬 Filmes de animação",cards((d?.movies||[]).slice(0,10)))}${section("🏆 Mais bem avaliados",cards((d?.top||FALLBACK).slice(0,10)))}${section("🎭 Gêneros",`<div class="genre-grid">${localGenres.map(g=>`<div class="genre" data-genre-name="${g}"><b>${g}</b><small style="display:block;color:#6689a8;margin-top:5px">Explorar catálogo</small></div>`).join("")}</div>`)}<div class="rail-card" style="margin-top:20px"><b>Sobre os dados</b><p style="color:#7695b3;font-size:11px;line-height:1.6">Este produto usa a API do TMDB, mas não é endossado ou certificado pelo TMDB. Posters, backdrops e metadados são carregados sob demanda pelo Worker.</p></div></div><aside class="right-rail">${rail(all)}</aside></div>`}
function rail(items){return `<div class="rail-card"><h3>🏆 Ranking</h3>${items.slice(0,6).map((p,i)=>`<div class="rank" data-id="${p.id}" data-type="${p.media_type}"><span class="rank-num">#${i+1}</span><img src="${img(p.poster_path,"w185")}" alt=""><div><b>${esc(p.title)}</b><small>${year(p)}</small><small class="rating">★ ${Number(p.vote_average||0).toFixed(1)}</small></div></div>`).join("")}</div><div class="rail-card"><h3>👤 Minha Conta</h3>${state.user?`<div class="user-row"><img class="avatar" src="${esc(state.avatar)}"><div><b>${esc(state.user.name)}</b><small>Conta sincronizável</small></div></div><div class="stat-grid" style="margin-top:12px"><div class="stat"><b>${state.list.length}</b><small>Minha lista</small></div><div class="stat"><b>${state.history.length}</b><small>Histórico</small></div></div>`:`<p style="color:#7895b3;font-size:11px;line-height:1.5">Crie uma conta para guardar preferências, favoritos e histórico.</p><button class="primary" style="width:100%" id="login-open">Criar conta</button>`}</div><div class="rail-card"><h3>🔄 Status</h3><div class="setting-row"><span style="font-size:11px">TMDB</span><b style="color:#20d99b;font-size:10px">● Proxy seguro</b></div><div class="setting-row"><span style="font-size:11px">Imagens</span><b style="color:#20d99b;font-size:10px">● CDN TMDB</b></div><div class="setting-row"><span style="font-size:11px">Player</span><b style="color:#20d99b;font-size:10px">● Independente</b></div></div>`}

async function catalogPage(kind="anime"){const anime=kind==="anime";return `<div class="page-title">${anime?"Catálogo de Animes":"Filmes"}</div><div class="subline">Dados reais do TMDB, carregados pelo Worker do AnimeDragon.</div><div class="filters"><button class="filter active" data-sort="popularity.desc">Populares</button><button class="filter" data-sort="vote_average.desc">Melhor avaliados</button><button class="filter" data-sort="first_air_date.desc">Novidades</button></div><div id="catalog-results">${skeletons(8)}</div>`}
function genresPage(){return `<div class="page-title">Gêneros</div><div class="subline">Escolha um gênero e o AnimeDragon consulta o catálogo do TMDB.</div><div class="genre-grid">${localGenres.map(g=>`<div class="genre" data-genre-name="${g}"><b>${g}</b><small style="display:block;color:#6689a8;margin-top:5px">Abrir busca</small></div>`).join("")}</div>`}
function calendar(){return `<div class="page-title">Calendário</div><div class="subline">Use a busca para encontrar lançamentos e séries. A agenda completa pode ser expandida com datas do TMDB.</div><div class="calendar">${["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"].map((d,i)=>`<div class="day"><strong>${d}</strong><div class="release"><b>${i%2?"Novo episódio":"Lançamento"}</b><small>Consultar catálogo</small></div></div>`).join("")}</div>`}
function listPage(){const items=state.home?.trending?.filter(x=>state.list.includes(x.title))||[];return `<div class="page-title">Minha Lista</div><div class="subline">Títulos salvos neste navegador.</div>${items.length?`<div class="catalog-grid">${items.map(card).join("")}</div>`:`<div class="empty">Sua lista está vazia. Abra um título e use “Minha Lista”.</div>`}`}
function historyPage(){if(!state.history.length)return '<div class="page-title">Histórico</div><div class="subline">Últimos títulos abertos neste navegador.</div><div class="empty">Nenhum título no histórico ainda.</div>';const html=state.history.map(t=>{const p=(state.home?.trending||[]).find(x=>x.title===t)||FALLBACK.find(x=>x.title===t)||{title:t,id:0,media_type:'tv'};return card(p)}).join('');return '<div class="page-title">Histórico</div><div class="subline">Últimos títulos abertos neste navegador.</div><div class="catalog-grid">'+html+'</div>'}

function profile(){const av=avatars.map(a=>'<button class="avatar-choice '+(state.avatar===a?'selected':'')+'" data-avatar="'+esc(a)+'"><img src="'+esc(a)+'"></button>').join('');return '<div class="page-title">Meu Perfil</div><div class="subline">Personalize sua conta AnimeDragon.</div><div class="profile-page"><section class="profile-cover"><img class="big-avatar" src="'+esc(state.avatar)+'"><h2>'+esc(state.user?.name||'Visitante')+'</h2><p style="color:#7895b3;font-size:11px">'+esc(state.user?.bio||'Sua área pessoal do AnimeDragon')+'</p><label class="secondary" style="display:block;text-align:center;margin-top:15px">Enviar avatar<input id="avatar-upload" type="file" accept="image/*" hidden></label></section><section class="rail-card" style="margin:0"><div class="tabs"><button class="tab active">Perfil</button></div><div class="form-grid"><div class="field"><label>Nome</label><input id="pf-name" value="'+esc(state.user?.name||'')+'"></div><div class="field"><label>E-mail</label><input id="pf-email" value="'+esc(state.user?.email||'')+'"></div><div class="field full"><label>Bio</label><textarea id="pf-bio">'+esc(state.user?.bio||'')+'</textarea></div><div class="full"><button class="primary" id="save-profile">Salvar perfil</button></div></div><h3 style="margin-top:22px">Escolha seu avatar</h3><div class="avatar-grid">'+av+'</div></section></div>'}

function settings(){return `<div class="page-title">Configurações</div><div class="subline">Preferências salvas localmente neste navegador.</div><div class="settings"><aside class="settings-nav"><button class="active">Preferências</button><button>Privacidade</button><button>TMDB</button><button>Sobre</button></aside><section class="rail-card" style="margin:0"><h2 style="font-size:16px">Reprodução e dados</h2>${[["Reprodução automática",true],["Legendas automáticas",true],["Notificar novos episódios",true],["Lembrar progresso",true],["Modo escuro",true],["Dados analíticos",false]].map(x=>`<div class="setting-row"><div><b style="font-size:12px">${x[0]}</b><small style="display:block;color:#6f8da9;margin-top:3px">Salvo automaticamente</small></div><button class="switch ${x[1]?"on":""}"></button></div>`).join("")}<div class="setting-row"><div><b style="font-size:12px">TMDB</b><small style="display:block;color:#6f8da9;margin-top:3px">A chave permanece no Worker e nunca é enviada ao navegador.</small></div><b style="color:#20d99b;font-size:10px">● Protegida</b></div></section></div>`}
function notifications(){return `<div class="page-title">Notificações</div><div class="subline">Central de atualizações do AnimeDragon.</div>${["Catálogo sincronizado com TMDB","Novos títulos encontrados","Preferências carregadas","Sistema de imagens online"].map((x,i)=>`<div class="rail-card"><b style="font-size:12px">${x}</b><small style="display:block;color:#6d8fac;margin-top:5px">Atualização ${i+1}</small></div>`).join("")}`}
function searchPage(){return `<div class="page-title">Busca</div><div class="subline">Resultados reais do TMDB para <b>${esc(state.search)}</b>.</div><div id="search-results">${skeletons(6)}</div>`}

async function render(){
 const p=state.page;let inner="";
 if(p==="home"){inner=state.home?home():`<div class="layout"><div>${skeletons(6)}${skeletons(6)}</div><aside class="right-rail">${skeletons(2)}</aside></div>`}
 else if(p==="anime")inner=await catalogPage("anime"); else if(p==="films")inner=await catalogPage("films"); else if(p==="genres")inner=genresPage(); else if(p==="calendar")inner=calendar(); else if(p==="list")inner=listPage(); else if(p==="history")inner=historyPage(); else if(p==="profile")inner=profile(); else if(p==="settings")inner=settings(); else if(p==="notifications")inner=notifications(); else if(p==="search")inner=searchPage(); else inner=home();
 $("#app").innerHTML=layout(inner);bind();
 if(p==="home"&&!state.home){state.home=await loadHome();render();return}
 if(p==="anime")loadCatalog("tv",true,"popularity.desc");
 if(p==="films")loadCatalog("movie",false,"popularity.desc");
 if(p==="search")loadSearch();
}

async function loadCatalog(type,anime,sort){try{const d=await api(`/api/tmdb/discover?type=${type}&anime=${anime?1:0}&sort=${encodeURIComponent(sort)}`);$("#catalog-results").innerHTML=`<div class="catalog-grid">${d.results.map(card).join("")}</div>`;bindCards()}catch(e){$("#catalog-results").innerHTML=`<div class="empty">${esc(e.message)}<br><br>Configure TMDB_API_KEY no Cloudflare.</div>`}}
async function loadSearch(){try{const d=await api(`/api/tmdb/search?q=${encodeURIComponent(state.search)}`);$("#search-results").innerHTML=d.results.length?`<div class="catalog-grid">${d.results.map(card).join("")}</div>`:`<div class="empty">Nenhum resultado encontrado.</div>`;bindCards()}catch(e){$("#search-results").innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function bindCards(){$$("[data-id]").forEach(c=>{if(c.dataset.bound)return;c.dataset.bound="1";c.onclick=()=>openDetails(c.dataset.id,c.dataset.type)})}
function bind(){
 $$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));
 bindCards();
 $$('[data-list-title]').forEach(b=>b.onclick=()=>toggleList(b.dataset.listTitle));
 $$('[data-genre-name]').forEach(b=>b.onclick=()=>{state.search=b.dataset.genreName;nav("search")});
 const gs=$("#global-search");if(gs)gs.onkeydown=e=>{if(e.key==="Enter"&&gs.value.trim()){state.search=gs.value.trim();nav("search")}};
 const login=$("#login-open");if(login)login.onclick=loginModal;
 const lo=$("#logout");if(lo)lo.onclick=()=>{state.user=null;store.set("ad_user",null);toast("Sessão encerrada");render()};
 const save=$("#save-profile");if(save)save.onclick=()=>{state.user={...(state.user||{}),name:$("#pf-name").value.trim()||"Usuário",email:$("#pf-email").value.trim(),bio:$("#pf-bio").value};store.set("ad_user",state.user);toast("Perfil salvo");render()};
 const up=$("#avatar-upload");if(up)up.onchange=e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2_500_000)return toast("Use uma imagem de até 2,5 MB","err");const r=new FileReader();r.onload=()=>{state.avatar=r.result;store.set("ad_avatar",state.avatar);toast("Avatar atualizado");render()};r.readAsDataURL(f)};
 $$(".avatar-choice").forEach(b=>b.onclick=()=>{state.avatar=b.dataset.avatar;store.set("ad_avatar",state.avatar);render()});
 $$(".switch").forEach(b=>b.onclick=()=>b.classList.toggle("on"));
 $$("[data-sort]").forEach(b=>b.onclick=()=>{const type=state.page==="films"?"movie":"tv";const anime=state.page==="anime";$$('[data-sort]').forEach(x=>x.classList.remove("active"));b.classList.add("active");loadCatalog(type,anime,b.dataset.sort)});
}
function toggleList(title){state.list=state.list.includes(title)?state.list.filter(x=>x!==title):[...state.list,title];store.set("ad_list",state.list);toast(state.list.includes(title)?"Adicionado à sua lista":"Removido da sua lista")}

async function openDetails(id,type){$("#modal-root").innerHTML=`<div class="modal-back"><div class="modal"><div class="modal-head"><span class="badge">CARREGANDO TMDB</span><button class="close" id="mclose">×</button></div><div style="padding:45px;text-align:center;color:#7d9ab5">Buscando informações, elenco, vídeos e temporadas...</div></div></div>`;$("#mclose").onclick=closeModal;try{const d=await api(`/api/tmdb/${type}/${id}`);const p=d.item;const seasons=type==="tv"?Array.from({length:p.number_of_seasons||0},(_,i)=>i+1):[];$("#modal-root").innerHTML=`<div class="modal-back"><div class="modal"><div class="modal-head"><div><span class="badge">TMDB • ${type==="movie"?"FILME":"SÉRIE"}</span><h2>${esc(p.title)}</h2><div class="subline">${year(p)} • ★ ${Number(p.vote_average||0).toFixed(1)} • ${esc(p.status||"")}</div></div><button class="close" id="mclose">×</button></div><div style="display:grid;grid-template-columns:190px 1fr;gap:20px"><img class="poster" src="${img(p.poster_path,"w500")}" style="border-radius:13px"><div><p style="color:#9ab1c8;line-height:1.65;font-size:12px">${esc(p.overview)}</p><div class="meta">${(p.genres||[]).map(g=>`<span>${esc(g.name)}</span>`).join("")}</div>${type==="tv"?`<div class="section-head"><h2>Temporadas</h2></div><div class="filters">${seasons.map((s,i)=>`<button class="filter ${i===0?"active":""}" data-season="${s}" data-tv="${p.id}">Temporada ${s}</button>`).join("")}</div><div id="episodes"><div class="empty">Escolha uma temporada.</div></div>`:`<button class="primary" data-play-title="${esc(p.title)}">▶ Abrir player</button>`}<div style="margin-top:18px"><button class="secondary" data-list-title="${esc(p.title)}">${state.list.includes(p.title)?"✓ Na minha lista":"＋ Minha lista"}</button></div></div></div></div></div>`;bindModal(p,type);if(type==="tv"&&seasons[0])loadSeason(p.id,seasons[0]);}catch(e){$("#modal-root").innerHTML=`<div class="modal-back"><div class="modal small"><div class="modal-head"><h2>Não foi possível carregar</h2><button class="close" id="mclose">×</button></div><p style="color:#9ab1c8">${esc(e.message)}</p></div></div>`;$("#mclose").onclick=closeModal}}
function bindModal(p,type){$("#mclose").onclick=closeModal;$$('[data-season]').forEach(b=>b.onclick=()=>{ $$('[data-season]').forEach(x=>x.classList.remove("active"));b.classList.add("active");loadSeason(p.id,b.dataset.season)});const play=$("[data-play-title]");if(play)play.onclick=()=>openPlayer(p.title,1)}
async function loadSeason(id,season){$("#episodes").innerHTML=`<div class="empty">Carregando episódios...</div>`;try{const d=await api(`/api/tmdb/tv/${id}/season/${season}`);$("#episodes").innerHTML=`<div class="episode-grid">${(d.season.episodes||[]).map(e=>`<button class="episode" data-ep-title="${esc(e.name||`Episódio ${e.episode_number}`)}" data-ep="${e.episode_number}"><b>EP ${e.episode_number}</b><small style="display:block;color:#6e91b0;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(e.name||"")}</small></button>`).join("")}</div>`;$$('[data-ep]').forEach(b=>b.onclick=()=>openPlayer(b.dataset.epTitle,+b.dataset.ep,season))}catch(e){$("#episodes").innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function closeModal(){$("#modal-root").innerHTML=""}
function openPlayer(title,ep=1,season=1){state.history=[title,...state.history.filter(x=>x!==title)].slice(0,30);store.set("ad_history",state.history);$("#modal-root").innerHTML=`<div class="player"><div class="player-top"><b>AnimeDragon • ${esc(title)} • T${season} E${ep}</b><button class="player-btn" id="player-close">✕ Fechar</button></div><div style="flex:1;display:grid;place-items:center;background:radial-gradient(circle,#08213d,#000)"><div style="text-align:center;max-width:520px;padding:25px"><img src="/assets/animedragon-dragon.png" style="width:110px;filter:drop-shadow(0 0 25px #09baff)"><h2>Player pronto para sua fonte licenciada</h2><p style="color:#7d95ad;font-size:12px;line-height:1.6">O catálogo e episódios vêm do TMDB. O TMDB fornece metadados e imagens, não os vídeos. Conecte aqui seu provedor de vídeo autorizado para reprodução real.</p><div><button class="primary" id="fs">⛶ Tela cheia</button></div></div></div><div class="player-bottom"><div class="player-progress"><i style="width:0"></i></div><div class="player-controls"><button class="player-btn">▶</button><button class="player-btn">⚙ Qualidade</button><button class="player-btn">CC Legendas</button><button class="player-btn">PT-BR Áudio</button></div></div></div>`;$("#player-close").onclick=closeModal;$("#fs").onclick=()=>document.querySelector(".player")?.requestFullscreen?.()}
function loginModal(){
 $("#modal-root").innerHTML=`<div class="modal-back"><div class="modal small"><div class="modal-head"><div><span class="badge">CONTA ANIMEDRAGON</span><h2>Entrar ou criar conta</h2></div><button class="close" id="mclose">×</button></div><div class="form-grid"><div class="field full"><label>Nome</label><input id="auth-name" placeholder="Seu nome"></div><div class="field full"><label>E-mail</label><input id="auth-email" type="email" placeholder="voce@email.com"></div><div class="full"><button class="primary" id="auth-submit" style="width:100%">Criar conta</button></div></div><small style="display:block;color:#617f9e;margin-top:14px">A conta desta versão fica no navegador. O banco D1 está preparado para a próxima etapa de autenticação server-side.</small></div></div>`;$("#mclose").onclick=closeModal;$("#auth-submit").onclick=()=>{const name=$("#auth-name").value.trim()||"Usuário";const email=$("#auth-email").value.trim()||"usuario@animedragon.local";state.user={name,email,bio:""};store.set("ad_user",state.user);closeModal();toast("Conta criada");render()}}

render();
