const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}};
const avatars=Array.from({length:12},(_,i)=>`/assets/avatars/avatar-${i+1}.svg`);
const avatarNames=['Guardião azul','Ninja do vento','Maga lunar','Espadachim solar','Raposa celeste','Alquimista','Viajante estelar','Sentinela','Feiticeira violeta','Ronin','Exploradora','Dragão de gelo'];
const genres=[['10759','Ação e aventura','⚡'],['10765','Fantasia e ficção','✦'],['35','Comédia','☀'],['18','Drama','◈'],['9648','Mistério','☾'],['10762','Infantil','✿']];
const icons={home:'<path d="m3 10 9-7 9 7v10H3z"/><path d="M9 20v-7h6v7"/>',anime:'<rect x="3" y="3" width="18" height="18" rx="3"/><path d="m10 8 6 4-6 4z"/>',genres:'<path d="m12 3 3 6 6 3-6 3-3 6-3-6-6-3 6-3z"/>',list:'<path d="M19 21 12 17 5 21V4h14z"/>',history:'<path d="M3 11a9 9 0 1 1 2 7M3 4v7h7M12 7v6l4 2"/>',profile:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',left:'<path d="m14 5-7 7 7 7"/>',right:'<path d="m10 5 7 7-7 7"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/>',logout:'<path d="M9 3H3v18h6M10 12h11m-5-5 5 5-5 5"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 10v7M12 6v1"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${icons[n]||icons.anime}</svg>`;
const fallback='/assets/poster-placeholder.svg';
const img=(path,size='w342')=>/^\/[\w.\/-]+$/.test(path||'')?`https://image.tmdb.org/t/p/${size}${path}`:fallback;
const year=p=>p.first_air_date?.slice(0,4)||'—';
const rating=p=>Number(p.vote_average||0)>0?Number(p.vote_average).toFixed(1):'—';
const state={user:null,avatar:avatars.includes(store.get('ad_avatar',''))?store.get('ad_avatar',''):avatars[0],home:null,items:new Map(),list:[],history:[],prefs:store.get('ad_preferences',{motion:true,economy:false}),details:null,episodes:[],season:1};
let renderVersion=0,modalVersion=0,seasonVersion=0,focusBeforeModal=null;
const pending=new Map(),cache=new Map();
function route(){const [page='home',query='']=(location.hash.slice(1)||'home').split('?');return {page,params:new URLSearchParams(query)}}
function nav(page){if(location.hash===`#${page}`)render();else location.hash=page}
function key(kind){return `ad_v7_${kind}_${state.user?.id||'guest'}`}
function loadPersonal(){state.list=store.get(key('list'),[]).filter(x=>x&&Number.isInteger(x.id)&&x.media_type==='tv');state.history=store.get(key('history'),[]).filter(x=>x&&Number.isInteger(x.id)&&x.media_type==='tv');remember([...state.list,...state.history]);}
function remember(items){items.forEach(p=>state.items.set(String(p.id),p))}
function toast(message,type='ok'){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;$('#toast-root').append(el);setTimeout(()=>el.remove(),4000)}
async function api(path,options={}){
 const get=!options.method||options.method==='GET', cached=cache.get(path);
 if(get&&cached&&cached.expires>Date.now())return cached.data;
 if(get&&pending.has(path))return pending.get(path);
 const promise=(async()=>{const response=await fetch(path,{credentials:'same-origin',...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...options.headers},signal:AbortSignal.timeout(15000)});const data=await response.json().catch(()=>({ok:false,error:'Resposta inválida do servidor.'}));if(!response.ok||data.ok===false)throw new Error(data.error||'Não foi possível concluir. Tente novamente.');if(get&&!path.startsWith('/api/auth')&&!path.startsWith('/api/playback')){if(cache.size>100)cache.delete(cache.keys().next().value);cache.set(path,{data,expires:Date.now()+300000})}return data})();
 if(get)pending.set(path,promise);try{return await promise}finally{if(get)pending.delete(path)}
}
const post=(path,data)=>api(path,{method:'POST',body:JSON.stringify(data)});
function applyPrefs(){document.documentElement.classList.toggle('reduce-motion',!state.prefs.motion);document.documentElement.classList.toggle('data-saver',!!state.prefs.economy)}
function imageTag(p,{size='w342',eager=false,cls='poster'}={}){return `<img class="${cls}" src="${img(p.poster_path,size)}" ${p.poster_path&&!state.prefs.economy?`srcset="${img(p.poster_path,'w185')} 185w, ${img(p.poster_path,'w342')} 342w, ${img(p.poster_path,'w500')} 500w" sizes="(max-width:600px) 43vw, 180px"`:''} width="342" height="513" loading="${eager?'eager':'lazy'}" decoding="async" ${eager?'fetchpriority="high"':''} alt="${esc(p.title)}">`}
function card(p){return `<button type="button" class="card" data-id="${p.id}" aria-label="Ver ${esc(p.title)}"><div class="poster-wrap">${imageTag(p)}<span class="card-score">★ ${rating(p)}</span><span class="card-play">▶</span></div><div class="card-body"><div class="card-title">${esc(p.title)}</div><div class="card-sub">${year(p)} <span>•</span> Anime</div></div></button>`}
function skeletons(){return `<div class="catalog-grid" aria-label="Carregando animes" aria-busy="true">${Array.from({length:8},()=>'<div class="card skeleton"><div class="poster"></div><div class="card-body">&nbsp;</div></div>').join('')}</div>`}
const empty=(title,text='',button='')=>`<div class="empty"><span class="empty-symbol">${icon('anime')}</span><h3>${title}</h3><p>${text}</p>${button}</div>`;
function section(id,title,subtitle,items){return `<section class="section"><div class="section-head"><div><h2>${title}</h2><p>${subtitle}</p></div><div class="rail-controls"><button class="icon-btn" data-scroll="${id}" data-dir="-1" aria-label="Voltar em ${title}">${icon('left')}</button><button class="icon-btn" data-scroll="${id}" data-dir="1" aria-label="Avançar em ${title}">${icon('right')}</button></div></div><div class="cards" id="${id}" tabindex="0" aria-label="${title}">${items.map(card).join('')}</div></section>`}
function brand(){return `<a class="brand" href="#home" aria-label="AnimeDragon, início"><img src="/assets/dragon-mark.webp" alt="" width="45" height="45"><strong>Anime<span>Dragon</span></strong></a>`}
function layout(inner){const current=route().page;const navs=[['home','Início'],['anime','Animes'],['genres','Gêneros'],['list','Minha lista'],['history','Histórico']];return `<div class="shell"><aside class="sidebar">${brand()}<div class="nav-title">Seu universo anime</div><nav class="nav" aria-label="Navegação principal">${navs.map(([id,name])=>`<a href="#${id}" class="${current===id?'active':''}" ${current===id?'aria-current="page"':''}>${icon(id)}<span>${name}</span></a>`).join('')}</nav><div class="sidebar-feature"><span class="badge">MODO ANIME</span><p>Uma nova história<br>espera por você.</p><a href="#anime">Explorar catálogo ${icon('right')}</a></div><div class="sidebar-bottom"><nav class="nav"><a href="#settings">${icon('settings')}<span>Preferências</span></a><a href="#about">${icon('info')}<span>Sobre</span></a></nav><div class="account-mini">${state.user?`<a href="#profile" class="user-row"><img class="avatar" src="${state.avatar}" alt=""><div><b>${esc(state.user.name)}</b><small>Meu perfil</small></div></a><button class="logout icon-btn" data-logout aria-label="Sair da conta">${icon('logout')}</button>`:`<a class="primary" href="#cadastro">Criar minha conta ${icon('right')}</a>`}</div></div></aside><main class="main"><header class="topbar"><a href="#home" class="mobile-brand" aria-label="Início"><img src="/assets/dragon-mark.webp" alt="AnimeDragon" width="36" height="36"></a><form class="search" id="search-form" role="search"><label class="sr-only" for="global-search">Buscar anime</label>${icon('search')}<input id="global-search" name="q" placeholder="Encontre seu próximo anime…" maxlength="120" value="${esc(route().params.get('q')||'')}"><kbd>↵</kbd></form><div class="top-actions">${state.user?`<a class="profile-chip" href="#profile"><img class="avatar" src="${state.avatar}" alt="Meu perfil"><div><b>${esc(state.user.name)}</b><small>Meu universo</small></div></a>`:`<a href="#entrar" class="login-link">Entrar</a><a href="#cadastro" class="primary compact">Criar conta</a>`}</div></header><div class="content">${inner}<footer class="site-footer"><span>AnimeDragon <span class="footer-dot">•</span> Seu universo de animes</span><a href="#about">Sobre e créditos</a></footer></div><nav class="mobile-nav" aria-label="Navegação no celular">${[...navs.slice(0,4),['profile','Perfil']].map(([id,name])=>`<a class="${current===id?'active':''}" href="#${id}">${icon(id)}<span>${name}</span></a>`).join('')}</nav></main></div>`}
function home(){const d=state.home,hero=d.trending[0];if(!hero)return empty('Ainda não há animes por aqui.','Tente novamente em instantes.');return `<div class="layout"><div class="home-main"><div class="eyebrow">EXPLORE. DESCUBRA. MARATONE.</div><section class="hero">${hero.backdrop_path?`<img class="hero-art" src="${img(hero.backdrop_path,state.prefs.economy?'w780':'w1280')}" alt="" width="1280" height="720" fetchpriority="high" decoding="async">`:'<img class="hero-dragon" src="/assets/dragon-art.webp" alt="">'}<div class="hero-content"><span class="badge"><i></i> EM DESTAQUE</span><h1>${esc(hero.title)}</h1><div class="meta"><span class="rating">★ ${rating(hero)}</span><span>${year(hero)}</span><span class="tag">ANIME</span></div><p>${esc(hero.overview||'Descubra os personagens e as aventuras desta história.')}</p><div class="actions"><button class="primary" data-id="${hero.id}">▶ Explorar anime</button><button class="secondary" data-list="${hero.id}">${state.list.some(x=>x.id===hero.id)?'✓ Na minha lista':'＋ Minha lista'}</button></div></div><div class="hero-index"><span>01</span> / EM DESTAQUE</div></section>${section('popular','Em alta','As histórias que estão conquistando o público',d.trending)}${section('recent','Novidades','Animes que estrearam recentemente',d.recent)}${section('top','Entre os melhores','Bem avaliados por quem também ama anime',d.top)}<section class="section"><div class="section-head"><div><h2>Qual é a sua vibe?</h2><p>Encontre sua próxima história por gênero</p></div><a href="#genres" class="text-link">Ver todos →</a></div>${genreTiles()}</section></div><aside class="right-rail"><div class="rail-card"><div class="rail-heading"><h3>Mais bem avaliados</h3><span>TOP 5</span></div>${d.top.slice(0,5).map((p,i)=>`<button class="rank" data-id="${p.id}"><span class="rank-num">${String(i+1).padStart(2,'0')}</span>${imageTag(p,{size:'w185'})}<div><b>${esc(p.title)}</b><small>${year(p)} · Anime</small><small class="rating">★ ${rating(p)}</small></div></button>`).join('')}</div><div class="rail-card dragon-callout"><img src="/assets/dragon-art.webp" alt="" width="160" height="160"><span class="badge">SEU PRÓXIMO CAPÍTULO</span><h3>Seu mundo.<br>Seu jeito.</h3><p>Escolha um avatar e dê vida ao seu perfil.</p><a href="#${state.user?'profile':'cadastro'}" class="secondary">${state.user?'Personalizar perfil':'Começar minha jornada'} →</a></div><div class="rail-card personal-stats"><h3>Sua coleção</h3><div class="stat-grid"><a href="#list" class="stat"><b>${state.list.length}</b><small>Na minha lista</small></a><a href="#history" class="stat"><b>${state.history.length}</b><small>No histórico</small></a></div><small>Salva neste navegador.</small></div></aside></div>`}
function genreTiles(){return `<div class="genre-grid">${genres.map(([id,name,symbol],i)=>`<a class="genre genre-${i}" href="#anime?genre=${id}"><span>${symbol}</span><b>${name}</b>${icon('right')}</a>`).join('')}</div>`}
function heading(title,subtitle){return `<div class="page-heading"><span class="eyebrow">ANIMEDRAGON</span><h1>${title}</h1><p>${subtitle}</p></div>`}
function listing(page,params){const search=page==='search',selected=params.get('genre')||'';return `${heading(search?'Encontre sua próxima história':(genres.find(g=>g[0]===selected)?.[1]||'Catálogo de animes'),search?`Buscando por “${esc(params.get('q')||'')}”`:'Só animes. Uma infinidade de mundos para explorar.')}<div class="catalog-toolbar">${!search?`<div class="filters">${[['popularity.desc','Populares'],['vote_average.desc','Melhor avaliados'],['first_air_date.desc','Novidades']].map(([v,l])=>`<button class="filter ${(params.get('sort')||'popularity.desc')===v?'active':''}" data-sort="${v}">${l}</button>`).join('')}</div><label class="select-label">Gênero<select id="genre-select"><option value="">Todos os gêneros</option>${genres.map(([id,name])=>`<option value="${id}" ${id===selected?'selected':''}>${name}</option>`).join('')}</select></label>`:''}</div><div id="catalog-results">${skeletons()}</div>`}
function collection(kind){const items=kind==='list'?state.list:state.history;return `${heading(kind==='list'?'Minha lista':'Meu histórico',kind==='list'?'As histórias que você quer acompanhar. Salvas neste navegador.':'Episódios iniciados por você neste navegador.')}<div class="collection-count">${items.length} ${items.length===1?'anime':'animes'}</div>${items.length?`<div class="catalog-grid">${items.map(card).join('')}</div>`:empty(kind==='list'?'Sua próxima aventura começa aqui.':'Nenhum episódio iniciado ainda.','Explore o catálogo e escolha um anime.', '<a class="primary" href="#anime">Explorar animes →</a>')}`}
function avatarPicker(selected=state.avatar){return `<div class="avatar-grid">${avatars.map((a,i)=>`<button type="button" class="avatar-choice ${a===selected?'selected':''}" data-avatar="${a}" aria-pressed="${a===selected}" aria-label="${avatarNames[i]}"><img src="${a}" alt="" width="80" height="80" loading="lazy"></button>`).join('')}</div>`}
function profile(){if(!state.user)return `${heading('Seu perfil, sua identidade','Entre na sua conta para escolher um avatar e personalizar seu perfil.')}${empty('Faça parte do AnimeDragon','Sua conta está esperando por você.','<a href="#entrar" class="primary">Entrar</a> <a href="#cadastro" class="secondary">Criar conta</a>')}`;return `${heading('Meu perfil','Um universo de histórias. Uma identidade só sua.')}<div class="profile-page"><section class="profile-cover"><img class="big-avatar" id="profile-avatar" src="${state.avatar}" alt="Seu avatar"><span class="badge">EXPLORADOR DE UNIVERSOS</span><h2>${esc(state.user.name)}</h2><p>${esc(state.user.bio||'Sempre pronto para a próxima aventura.')}</p><button class="secondary" data-logout>Sair da conta</button></section><section class="rail-card"><form id="profile-form"><div class="form-grid"><div class="field"><label for="pf-name">Nome de usuário</label><input id="pf-name" value="${esc(state.user.name)}" minlength="3" maxlength="30" required></div><div class="field"><label for="pf-email">E-mail da conta</label><input id="pf-email" value="${esc(state.user.email)}" type="email" readonly></div><div class="field full"><label for="pf-bio">Sua bio</label><textarea id="pf-bio" maxlength="300" placeholder="Conte um pouco sobre seu universo…">${esc(state.user.bio)}</textarea></div></div><h3 class="avatar-title">Escolha sua versão anime</h3>${avatarPicker()}<p id="profile-error" role="alert" class="form-error"></p><button class="primary" type="submit">Salvar alterações</button></form></section></div>`}
function settings(){return `${heading('Do seu jeito','Preferências que ficam salvas neste navegador.')}<section class="rail-card settings-card">${[['motion','Animações da interface','Transições suaves e efeitos visuais.'],['economy','Economizar dados','Capas menores para conexões mais lentas.']].map(([id,title,description])=>`<div class="setting-row"><div><b>${title}</b><p>${description}</p></div><button class="switch ${state.prefs[id]?'on':''}" role="switch" aria-checked="${!!state.prefs[id]}" aria-label="${title}" data-pref="${id}"></button></div>`).join('')}</section>`}
function about(){return `${heading('Feito para quem vive anime','AnimeDragon é o seu espaço para descobrir e organizar suas próximas histórias.')}<section class="rail-card about-card"><h2>Sobre o catálogo</h2><p>O catálogo reúne séries de animação japonesas. A disponibilidade de um título no catálogo não significa que seus episódios estejam disponíveis para reprodução.</p><h2>Sua conta e seus dados</h2><p>Seu cadastro e perfil ficam na conta. Sua lista, histórico e preferências são salvos neste navegador e separados por usuário. Limpar os dados do navegador apaga essas coleções locais.</p><h2>Créditos de dados e imagens</h2><a href="https://www.themoviedb.org" target="_blank" rel="noopener"><img class="tmdb-logo" src="https://www.themoviedb.org/assets/2/v4/logos/v2/blue_square_2-d537fb228cf3ded904ef09b136fe3fec72548ebc1fea3fbbd1ad9e36364db38b.svg" alt="TMDB" width="85" height="62"></a><p>This product uses the TMDB API but is not endorsed or certified by TMDB.</p><p>Avatares ilustrados exclusivos do AnimeDragon.</p></section>`}
function authPage(login){return `<main class="auth-shell"><section class="auth-world">${brand()}<div class="auth-orbit orbit-one"></div><div class="auth-orbit orbit-two"></div><div class="auth-sparks" aria-hidden="true">${Array.from({length:10},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div><div class="auth-world-copy"><span class="badge">SEU PORTAL PARA OUTROS MUNDOS</span><h1>Uma conta.<br>Infinitas <em>aventuras.</em></h1><p>Encontre sua próxima história.<br>O próximo capítulo começa com você.</p></div><img class="auth-dragon" src="/assets/dragon-art.webp" alt="Dragão azul do AnimeDragon" width="620" height="620" fetchpriority="high"><div class="auth-world-bottom"><span>✦ Só animes</span><span>◈ Seu próprio avatar</span><span>♡ Sua coleção</span></div></section><section class="auth-panel"><a class="back-link" href="#home">${icon('left')} Voltar ao início</a><div class="auth-form-wrap"><span class="eyebrow">${login?'BEM-VINDO DE VOLTA':'SUA JORNADA COMEÇA AQUI'}</span><h2>${login?'Entre no seu universo.':'Crie sua conta.'}</h2><p>${login?'Seus animes e seu perfil estão esperando.':'Escolha sua identidade e descubra novas histórias.'}</p><div class="auth-tabs"><a href="#cadastro" class="${login?'':'active'}">Criar conta</a><a href="#entrar" class="${login?'active':''}">Entrar</a></div><form id="auth-form" data-mode="${login?'login':'register'}">${login?'':`<div class="field"><label for="auth-name">Nome de usuário</label><input id="auth-name" name="name" placeholder="Seu nome no universo anime" autocomplete="nickname" minlength="3" maxlength="30" required></div>`}<div class="field"><label for="auth-email">E-mail</label><input id="auth-email" name="email" type="email" placeholder="voce@exemplo.com" autocomplete="email" maxlength="254" required></div><div class="field"><label for="auth-password">Senha</label><div class="password-field"><input id="auth-password" name="password" type="password" placeholder="${login?'Sua senha':'Pelo menos 12 caracteres'}" autocomplete="${login?'current-password':'new-password'}" minlength="${login?1:12}" maxlength="128" required><button type="button" id="password-toggle" aria-label="Mostrar senha">Mostrar</button></div></div>${login?'':`<div class="field"><label for="auth-confirm">Confirme sua senha</label><input id="auth-confirm" name="confirm" type="password" autocomplete="new-password" required placeholder="Repita sua senha"></div><div class="auth-avatar-heading"><b>Escolha seu avatar</b><span>Você pode mudar depois</span></div>${avatarPicker()}`}<p id="auth-error" role="alert" class="form-error"></p><button class="primary auth-submit" type="submit">${login?'Entrar no AnimeDragon':'Começar minha jornada'} ${icon('right')}</button></form><p class="auth-footnote">${login?'Ainda não tem uma conta? <a href="#cadastro">Crie a sua</a>':'Já faz parte desse universo? <a href="#entrar">Entre aqui</a>'}</p></div><small class="auth-copyright">AnimeDragon · Cada história é um novo começo.</small></section></main>`}

async function render(){const version=++renderVersion,{page,params}=route();closeModal();document.title=page==='cadastro'?'Criar conta · AnimeDragon':page==='entrar'?'Entrar · AnimeDragon':'AnimeDragon';let inner;
 if(['cadastro','entrar'].includes(page)){$('#app').innerHTML=authPage(page==='entrar');bind();window.scrollTo(0,0);return}
 if(page==='home')inner=state.home?home():skeletons();
 else if(page==='anime'||page==='search')inner=listing(page,params);
 else if(page==='genres')inner=heading('Explore por gênero','Qual mundo você quer descobrir hoje?')+genreTiles();
 else if(page==='list'||page==='history')inner=collection(page);
 else if(page==='profile')inner=profile();else if(page==='settings')inner=settings();else if(page==='about')inner=about();
 else{nav('home');return}
 $('#app').innerHTML=layout(inner);bind();window.scrollTo(0,0);
 if(page==='home'&&!state.home){try{const data=await api('/api/catalog/home');state.home=data;remember([...data.trending,...data.top,...data.recent]);migrateLists();if(version===renderVersion)render()}catch(e){if(version===renderVersion){$('.content').innerHTML=empty('O catálogo deu uma pausa.',esc(e.message),'<button class="primary" id="retry-home">Tentar novamente</button>');$('#retry-home').onclick=()=>render()}}}
 if(page==='anime'||page==='search')loadCatalog(page,params,version);
}
function migrateLists(){if(store.get('ad_v7_migrated',false))return;const old=store.get('ad_list',[]);if(Array.isArray(old)){for(const title of old){const p=[...state.items.values()].find(x=>x.title===title);if(p&&!state.list.some(x=>x.id===p.id))state.list.push(p)}store.set(key('list'),state.list)}store.set('ad_v7_migrated',true)}
async function loadCatalog(page,params,version){const path=page==='search'?`/api/catalog/search?${params}`:`/api/catalog/discover?${params}`;try{const data=await api(path);if(version!==renderVersion)return;remember(data.results);$('#catalog-results').innerHTML=(data.results.length?`<div class="catalog-grid">${data.results.map(card).join('')}</div>`:empty('Nenhum anime nesta página.','Tente outro nome, filtro ou avance a página.'))+`<nav class="pagination" aria-label="Páginas do catálogo"><button class="secondary" data-page="${data.page-1}" ${data.page<=1?'disabled':''}>${icon('left')} Anterior</button><span>Página ${data.page} de ${Math.max(data.page,data.totalPages)}</span><button class="secondary" data-page="${data.page+1}" ${data.page>=data.totalPages?'disabled':''}>Próxima ${icon('right')}</button></nav>`;bindCards();$$('[data-page]').forEach(b=>b.onclick=()=>{params.set('page',b.dataset.page);nav(`${page}?${params}`)})}catch(e){if(version===renderVersion){$('#catalog-results').innerHTML=empty('Não foi possível carregar.',esc(e.message),'<button class="primary" id="retry-catalog">Tentar novamente</button>');$('#retry-catalog').onclick=()=>loadCatalog(page,params,version)}}}
function toggleList(id){const p=state.items.get(String(id));if(!p)return;const found=state.list.some(x=>x.id===p.id);state.list=found?state.list.filter(x=>x.id!==p.id):[p,...state.list];store.set(key('list'),state.list);$$(`[data-list="${id}"]`).forEach(b=>b.textContent=found?'＋ Minha lista':'✓ Na minha lista');toast(found?'Removido da sua lista':'Adicionado à sua lista');if(route().page==='list')render()}
function bindCards(){$$('[data-id]').forEach(b=>b.onclick=()=>openDetails(b.dataset.id));$$('[data-list]').forEach(b=>b.onclick=()=>toggleList(b.dataset.list))}
function bind(){bindCards();const search=$('#search-form');if(search)search.onsubmit=e=>{e.preventDefault();const q=$('#global-search').value.trim();if(q)nav(`search?q=${encodeURIComponent(q)}`)};
 $$('[data-scroll]').forEach(b=>b.onclick=()=>{const rail=document.getElementById(b.dataset.scroll);rail.scrollBy({left:Number(b.dataset.dir)*rail.clientWidth*.85,behavior:reducedMotion()?'instant':'smooth'})});
 $$('.cards').forEach(rail=>{const update=()=>{$$(`[data-scroll="${rail.id}"]`).forEach(b=>b.disabled=Number(b.dataset.dir)<0?rail.scrollLeft<2:rail.scrollLeft+rail.clientWidth>=rail.scrollWidth-2)};rail.addEventListener('scroll',update,{passive:true});rail.onkeydown=e=>{if(e.target!==rail)return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();rail.scrollBy({left:(e.key==='ArrowRight'?1:-1)*200,behavior:reducedMotion()?'instant':'smooth'})}};requestAnimationFrame(update)});
 $$('[data-sort]').forEach(b=>b.onclick=()=>{const p=route().params;p.set('sort',b.dataset.sort);p.delete('page');nav(`anime?${p}`)});const genre=$('#genre-select');if(genre)genre.onchange=()=>{const p=route().params;p.delete('page');genre.value?p.set('genre',genre.value):p.delete('genre');nav(`anime?${p}`)};
 $$('[data-avatar]').forEach(b=>b.onclick=()=>{state.avatar=b.dataset.avatar;$$('[data-avatar]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))});if($('#profile-avatar'))$('#profile-avatar').src=state.avatar});
 $$('[data-logout]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await post('/api/auth/logout',{});state.user=null;state.avatar=avatars[0];loadPersonal();nav('home');toast('Você saiu da conta.')}catch(e){toast(e.message,'err');b.disabled=false}});
 $$('[data-pref]').forEach(b=>b.onclick=()=>{const k=b.dataset.pref;state.prefs[k]=!state.prefs[k];store.set('ad_preferences',state.prefs);b.classList.toggle('on',state.prefs[k]);b.setAttribute('aria-checked',String(state.prefs[k]));applyPrefs()});
 const form=$('#auth-form');if(form)form.onsubmit=submitAuth;
 const toggle=$('#password-toggle');if(toggle)toggle.onclick=()=>{const input=$('#auth-password');input.type=input.type==='password'?'text':'password';toggle.textContent=input.type==='password'?'Mostrar':'Ocultar';toggle.setAttribute('aria-label',`${toggle.textContent} senha`)};
 const profileForm=$('#profile-form');if(profileForm)profileForm.onsubmit=async e=>{e.preventDefault();const button=$('button[type=submit]',profileForm);button.disabled=true;$('#profile-error').textContent='';try{const d=await post('/api/auth/profile',{name:$('#pf-name').value,bio:$('#pf-bio').value,avatar:state.avatar});state.user=d.user;state.avatar=d.user.avatar;store.set('ad_avatar',state.avatar);toast('Perfil atualizado!');render()}catch(err){$('#profile-error').textContent=err.message;button.disabled=false}};
}
async function submitAuth(e){e.preventDefault();const form=e.currentTarget,mode=form.dataset.mode,error=$('#auth-error'),button=$('button[type=submit]',form);error.textContent='';const password=$('#auth-password').value;if(mode==='register'&&password!==$('#auth-confirm').value){error.textContent='As senhas precisam ser iguais.';$('#auth-confirm').focus();return}const values={email:$('#auth-email').value,password,avatar:state.avatar,...(mode==='register'?{name:$('#auth-name').value}:{})};button.disabled=true;button.textContent=mode==='register'?'Criando sua conta…':'Entrando…';try{const d=await post(`/api/auth/${mode}`,values);state.user=d.user;state.avatar=d.user.avatar;store.set('ad_avatar',state.avatar);loadPersonal();toast(mode==='register'?'Sua conta foi criada!':'Bem-vindo de volta!');nav('home')}catch(err){if(form.isConnected){error.textContent=err.message;button.disabled=false;button.textContent=mode==='register'?'Começar minha jornada →':'Entrar no AnimeDragon →'}}}
function reducedMotion(){return !state.prefs.motion||matchMedia('(prefers-reduced-motion: reduce)').matches}

function setModal(content){$('#modal-root').innerHTML=`<div class="modal-back"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="detail-title" tabindex="-1">${content}</section></div>`;document.body.classList.add('modal-open');$('#app').inert=true;$('#modal-root .modal').focus();$('#modal-root .modal-back').onclick=e=>{if(e.target===e.currentTarget)closeModal()};$('#mclose').onclick=closeModal;}
const closeButton=()=>`<button class="close" id="mclose" aria-label="Fechar detalhes">${icon('close')}</button>`;
async function openDetails(id,preferredSeason){focusBeforeModal=document.activeElement;const version=++modalVersion;++seasonVersion;state.details=null;setModal(`<div class="modal-head"><h2 id="detail-title">Carregando anime…</h2>${closeButton()}</div><div class="detail-loading skeleton"></div>`);try{const d=await api(`/api/catalog/tv/${id}`);if(version!==modalVersion)return;const p=d.item;state.details=p;remember([p]);const seasons=p.seasons||[];state.season=seasons.some(s=>s.season_number===Number(preferredSeason))?Number(preferredSeason):(seasons.find(s=>s.season_number>0)?.season_number??seasons[0]?.season_number??0);setModal(`<div class="modal-head"><span class="badge">ANIME · ${year(p)}</span>${closeButton()}</div><div class="detail-summary">${imageTag(p,{eager:true})}<div class="detail-copy"><h2 id="detail-title">${esc(p.title)}</h2><div class="meta"><span class="rating">★ ${rating(p)}</span><span>${p.number_of_episodes} episódios cadastrados</span><span>${({'Ended':'Concluído','Returning Series':'Em lançamento','Canceled':'Cancelado','In Production':'Em produção','Planned':'Anunciado'})[p.status]||''}</span></div><p class="synopsis">${esc(p.overview||'Sinopse ainda não disponível.')}</p><div class="genre-tags">${p.genres.map(g=>`<span>${esc(g.name)}</span>`).join('')}</div><button class="secondary" data-list="${p.id}">${state.list.some(x=>x.id===p.id)?'✓ Na minha lista':'＋ Minha lista'}</button></div></div><div class="episodes-heading"><div><span class="eyebrow">CONTINUE A HISTÓRIA</span><h3>Temporadas e episódios</h3></div><label class="select-label">Temporada<select id="season-select">${seasons.map(s=>`<option value="${s.season_number}" ${s.season_number===state.season?'selected':''}>${s.season_number===0?'Especiais':`Temporada ${s.season_number}`} · ${s.episode_count} ep.</option>`).join('')}</select></label></div><div class="episode-toolbar"><label class="episode-search">${icon('search')}<input id="episode-search" type="search" placeholder="Buscar número ou nome do episódio" aria-label="Buscar episódio"></label><label class="select-label">Ordem<select id="episode-order"><option value="asc">Primeiro ao último</option><option value="desc">Último ao primeiro</option></select></label></div><div id="episodes" aria-live="polite"></div>`);bindCards();$('#season-select').disabled=!seasons.length;$('#season-select').onchange=e=>loadSeason(p.id,Number(e.target.value));$('#episode-search').oninput=renderEpisodes;$('#episode-order').onchange=renderEpisodes;if(seasons.length)loadSeason(p.id,state.season);else $('#episodes').innerHTML=empty('Temporadas ainda não cadastradas.');}catch(e){if(version!==modalVersion)return;setModal(`<div class="modal-head"><h2 id="detail-title">Não foi possível abrir</h2>${closeButton()}</div>${empty('Tente novamente em instantes.',esc(e.message),`<button class="primary" id="retry-details">Tentar novamente</button>`)}`);const retry=$('#retry-details');if(retry)retry.onclick=()=>openDetails(id)}}
async function loadSeason(id,season){const version=++seasonVersion,modal=modalVersion;state.season=season;state.episodes=[];$('#episode-search').value='';$('#episodes').innerHTML='<div class="empty" aria-busy="true">Carregando episódios…</div>';try{const d=await api(`/api/catalog/tv/${id}/season/${season}`);if(version!==seasonVersion||modal!==modalVersion)return;state.episodes=d.season.episodes;renderEpisodes()}catch(e){if(version===seasonVersion&&modal===modalVersion){$('#episodes').innerHTML=empty('Não foi possível carregar os episódios.',esc(e.message),'<button class="primary" id="retry-season">Tentar novamente</button>');$('#retry-season').onclick=()=>loadSeason(id,season)}}}
function renderEpisodes(){if(!$('#episodes'))return;const q=$('#episode-search').value.toLocaleLowerCase('pt-BR').trim(),desc=$('#episode-order').value==='desc';const episodes=state.episodes.filter(e=>String(e.episode_number)===q||e.name?.toLocaleLowerCase('pt-BR').includes(q)||!q).sort((a,b)=>(desc?-1:1)*(a.episode_number-b.episode_number));$('#episodes').innerHTML=`<div class="episode-count">${episodes.length} ${episodes.length===1?'episódio':'episódios'}${q?' encontrados':''}</div>`+(episodes.length?`<div class="episode-grid">${episodes.map(e=>{const future=e.air_date&&e.air_date>new Date().toISOString().slice(0,10);return `<button class="episode" data-episode="${e.episode_number}" ${future?'disabled':''}><span class="episode-number">${String(e.episode_number).padStart(2,'0')}</span><span class="episode-info"><b>${esc(e.name||`Episódio ${e.episode_number}`)}</b><small>${e.runtime?`${e.runtime} min · `:''}${future?'Previsto para ':''}${e.air_date?new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(e.air_date+'T12:00:00Z')):'Data não informada'}</small></span><span class="episode-play">${future?'◷':'▶'}</span></button>`}).join('')}</div>`:empty('Nenhum episódio encontrado.',q?'Tente outro nome ou número.':'Esta temporada ainda não tem episódios cadastrados.'));$$('[data-episode]').forEach(b=>b.onclick=()=>openPlayer(Number(b.dataset.episode)))}
function closeModal(){++modalVersion;++seasonVersion;const had=!!$('#modal-root').innerHTML;$('#modal-root').innerHTML='';document.body.classList.remove('modal-open');$('#app').inert=false;if(had&&focusBeforeModal?.isConnected)focusBeforeModal.focus()}
async function openPlayer(episode){const p=state.details,season=state.season;if(!p)return;const version=++modalVersion;setModal(`<div class="modal-head"><div><span class="eyebrow">TEMPORADA ${season} · EPISÓDIO ${episode}</span><h2 id="detail-title">${esc(p.title)}</h2></div>${closeButton()}</div><div id="playback-body" class="playback-body"><div class="empty">Preparando episódio…</div></div><button class="secondary" id="back-episodes">${icon('left')} Voltar aos episódios</button>`);$('#back-episodes').onclick=()=>openDetails(p.id,season);try{const source=await api(`/api/playback?id=${p.id}&season=${season}&episode=${episode}`);if(version!==modalVersion)return;if(!source.available){$('#playback-body').innerHTML=empty('Este episódio ainda não está disponível.','Você pode adicioná-lo à sua lista e explorar outros animes.');return}$('#playback-body').innerHTML=`<video id="anime-video" controls playsinline preload="metadata" crossorigin="anonymous" poster="${img(p.backdrop_path,'w780')}"><source src="${esc(source.url)}" type="${esc(source.type)}">${source.subtitles.map(t=>`<track kind="subtitles" src="${esc(t.src)}" srclang="${esc(t.language||'pt')}" label="${esc(t.label||'Português')}">`).join('')}</video><p id="video-status" role="status"></p>`;const video=$('#anime-video'),previous=state.history.find(x=>x.id===p.id&&x.season===season&&x.episode===episode);video.onloadedmetadata=()=>{if(previous?.progress&&previous.progress<video.duration-10)video.currentTime=previous.progress};let last=0;const save=()=>{const entry={...p,season,episode,progress:Math.floor(video.currentTime),duration:Math.floor(video.duration)||0};state.history=[entry,...state.history.filter(x=>x.id!==p.id)].slice(0,50);store.set(key('history'),state.history)};video.onplay=save;video.onpause=()=>{if(video.currentTime>0)save()};video.ontimeupdate=()=>{if(Date.now()-last>5000&&!video.paused){last=Date.now();save()}};video.onerror=()=>{$('#video-status').textContent='Não foi possível reproduzir este vídeo. A fonte pode estar indisponível ou o formato não ser compatível.'};video.onended=()=>{save();const next=state.episodes.find(e=>e.episode_number===episode+1);if(next){const button=document.createElement('button');button.className='primary';button.textContent='Próximo episódio →';button.onclick=()=>openPlayer(next.episode_number);$('#video-status').replaceChildren(button)}}}catch(e){if(version===modalVersion)$('#playback-body').innerHTML=empty('Não foi possível preparar o vídeo.',esc(e.message))}}

window.addEventListener('hashchange',render);
window.addEventListener('resize',()=>$$('.cards').forEach(r=>r.dispatchEvent(new Event('scroll'))));
document.addEventListener('error',e=>{if(e.target instanceof HTMLImageElement&&!e.target.dataset.fallback){e.target.dataset.fallback='1';e.target.removeAttribute('srcset');e.target.src=fallback}},true);
document.addEventListener('keydown',e=>{const modal=$('#modal-root .modal');if(!modal)return;if(e.key==='Escape'){e.preventDefault();closeModal()}if(e.key==='Tab'){const nodes=$$('button:not([disabled]),a[href],input,select,video[controls],[tabindex="0"]',modal);const first=nodes[0],last=nodes.at(-1);if(!first){e.preventDefault();return}if(e.shiftKey&&(document.activeElement===first||document.activeElement===modal)){e.preventDefault();last.focus()}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===modal)){e.preventDefault();first.focus()}}});
applyPrefs();loadPersonal();render();
api('/api/auth/me').then(d=>{if(d.user){state.user=d.user;state.avatar=d.user.avatar;loadPersonal();if(!['cadastro','entrar'].includes(route().page)&&!$('#modal-root').innerHTML)render()}}).catch(()=>{});
