import test from 'node:test';
import assert from 'node:assert/strict';
import {addonEpisodes,addonPlayback,publicHttps} from '../server/addon.js';
const anime={id:123,external_ids:{imdb_id:'tt123'}};
const env={STREMIO_MANIFEST_URL:'https://addon.test/manifest.json',ASSETS:{fetch:async()=>Response.json({})}};
let streams=[{url:'https://media.example.org/episode.m3u8',name:'HD',subtitles:[{url:'https://media.example.org/pt.vtt',lang:'pt'}]},{infoHash:'abc'},{url:'http://insecure.example.org/e.mp4'},{url:'https://media.example.org/proxy',behaviorHints:{proxyHeaders:{request:{Referer:'x'}}}}];
const calls=[];
globalThis.fetch=async url=>{const u=new URL(url);calls.push(u);if(u.pathname.endsWith('/manifest.json'))return Response.json({resources:['meta','stream'],types:['series'],idPrefixes:['tt']});if(u.pathname.includes('/meta/'))return Response.json({meta:{id:'tt123',videos:[{id:'tt123:3:2',season:3,episode:2,title:'Segundo episódio',released:'2026-09-01',thumbnail:'https://images.example.org/e2.jpg'}]}});if(u.pathname.includes('/stream/'))return Response.json({streams});throw Error('Unexpected request')};
test('addon metadata preserves provider episode IDs and real season numbers',async()=>{const data=await addonEpisodes(anime,env,'https://anime.test');assert.equal(data[0].id,'tt123:3:2');assert.equal(data[0].season_number,3);assert.equal(data[0].episode_number,2);assert.match(data[0].thumbnail,/e2.jpg/)});
test('playback resolves exact episode and offers only browser-compatible HTTPS sources',async()=>{const d=await addonPlayback(anime,3,2,env,'https://anime.test');assert.equal(d.available,true);assert.equal(d.streams.length,1);assert.equal(d.type,'application/vnd.apple.mpegurl');assert.equal(d.subtitles[0].language,'pt');assert.ok(calls.at(-1).pathname.includes('tt123%3A3%3A2'))});
test('missing provider episode does not silently play another episode',async()=>{const d=await addonPlayback(anime,2,1,env,'https://anime.test');assert.equal(d.available,false)});
test('unknown anime identity remains unavailable instead of a title-based guess',async()=>{const d=await addonPlayback({id:444},1,1,env,'https://anime.test');assert.equal(d.available,false)});
test('source filtering rejects private, malformed and credential-bearing URLs',()=>{for(const url of ['http://example.org/a','https://localhost/a','https://127.0.0.1/a','https://10.0.1.2/a','https://user:password@example.org/a','javascript:alert(1)'])assert.equal(publicHttps(url),false);assert.equal(publicHttps('https://media.example.org/a.mp4'),true)});
