import http from 'node:http';
import {DatabaseSync} from 'node:sqlite';
import {readFile,mkdir} from 'node:fs/promises';
import {resolve,dirname,extname} from 'node:path';
import {fileURLToPath} from 'node:url';
import worker from '../worker.js';
import {demoResponse} from '../server/demo.js';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
await mkdir(resolve(root,'.local'),{recursive:true});
const sqlite=new DatabaseSync(resolve(root,'.local/animedragon.sqlite'));
const DB={prepare(sql){let args=[];return {bind(...values){args=values;return this},async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return {results:sqlite.prepare(sql).all(...args)}},async run(){const r=sqlite.prepare(sql).run(...args);return {meta:{changes:r.changes}}}}},async batch(statements){sqlite.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.run());sqlite.exec('COMMIT');return result}catch(e){sqlite.exec('ROLLBACK');throw e}}};
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.svg':'image/svg+xml','.webp':'image/webp','.png':'image/png'};
const demo=!process.env.TMDB_API_KEY;
async function asset(request){let path=decodeURIComponent(new URL(request.url).pathname);if(path==='/')path='/index.html';const target=resolve(root,'web','.'+path);if(!target.startsWith(resolve(root,'web')+ '/'.replace('/',process.platform==='win32'?'\\':'/')))return new Response('Forbidden',{status:403});try{let data=await readFile(target);if(demo&&path==='/index.html')data=data.toString().replace('<body>','<body><div class="demo-banner">PRÉVIA LOCAL · Catálogo ilustrativo original. Contas e interações funcionam com banco local. Vídeos não incluídos.</div>');return new Response(data,{headers:{'Content-Type':types[extname(target)]||'application/octet-stream','Cache-Control':'no-store'}})}catch{return new Response('Not found',{status:404})}}
const nativeFetch=globalThis.fetch;
globalThis.fetch=(input,options)=>demo&&String(input).startsWith('https://api.themoviedb.org/')?Promise.resolve(demoResponse(input)):nativeFetch(input,options);
const env={DB,ASSETS:{fetch:asset},TMDB_API_KEY:process.env.TMDB_API_KEY||'local-demo',...(process.env.AUTH_SECRET?{AUTH_SECRET:process.env.AUTH_SECRET}:{})};
let queue=Promise.resolve();
const server=http.createServer((req,res)=>{const handle=async()=>{try{const chunks=[];let bytes=0;for await(const c of req){bytes+=c.length;if(bytes>1500000){res.writeHead(413);res.end();return}chunks.push(c)}const origin=`http://${req.headers.host}`;const request=new Request(origin+req.url,{method:req.method,headers:req.headers,...(!['GET','HEAD'].includes(req.method)?{body:Buffer.concat(chunks)}:{})});let response;if(demo&&req.url.startsWith('/api/playback'))response=Response.json({ok:true,available:false,reason:'Esta prévia usa histórias ilustrativas. Configure fontes de vídeo para reproduzir o catálogo real.'});else response=await worker.fetch(request,env,{waitUntil:p=>p.catch(console.error)});res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()))}catch(e){console.error(e);res.writeHead(500);res.end('Erro local. Consulte o terminal.')}};queue=queue.then(handle,handle)});
const port=Number(process.env.PORT||8787);server.listen(port,'127.0.0.1',()=>console.log(`AnimeDragon: http://127.0.0.1:${port}\n${demo?'Prévia local: catálogo ilustrativo; contas reais no SQLite local.':'Catálogo TMDB configurado.'}`));
