import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {livingDragon,bindDragon} from '../web/js/dragon.js';
const {parseHTML}=await import(process.env.ANIMEDRAGON_DOM_MODULE||'linkedom');
const fixture={id:1,title:'Anime & teste',overview:'Uma aventura de teste',media_type:'tv',poster_path:'/poster.jpg',backdrop_path:'/back.jpg',first_air_date:'2026-01-01',vote_average:8.5,genres:[],number_of_episodes:2,seasons:[{season_number:1,episode_count:2}]};
function setup(){
 const {window,document}=parseHTML('<html><head></head><body><div id="app"></div><div id="modal-root"></div><div id="toast-root"></div></body></html>');
 window.scrollTo=()=>{};window.HTMLElement.prototype.scrollIntoView=function(){};window.HTMLElement.prototype.scrollBy=function(){};
 const memory=new Map(),calls=[];
 const context=vm.createContext({console,window,document,location:{hash:'#home'},URLSearchParams,AbortSignal,Date,Intl,Map,HTMLImageElement:window.HTMLImageElement,matchMedia:()=>({matches:true}),livingDragon,bindDragon:()=>bindDragon(document),requestAnimationFrame:cb=>cb(),setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)},fetch:async(path,options={})=>{calls.push({path,options});if(path.includes('/api/community/'))return Response.json({ok:true,likes:0,dislikes:0,reaction:0,collections:[],comments:[],total:0,items:[]});if(path.includes('/recommendations'))return Response.json({ok:true,results:[{...fixture,id:2,title:'Anime parecido'}]});if(path.includes('/season/'))return Response.json({ok:true,season:{episodes:[{episode_number:1,name:'Começo',still_path:'/ep.jpg',air_date:'2026-01-01'},{episode_number:2,name:'Continuação',air_date:'2026-01-02'}]}});if(path.includes('/api/catalog/tv/'))return Response.json({ok:true,item:fixture});if(path.includes('/api/auth/register'))return Response.json({ok:true,user:{id:'u1',name:'Testador',email:'test@example.com',avatar:'/assets/avatars/avatar-1.svg'}});return Response.json({ok:true})}});
 let code=readFileSync(new URL('../web/js/app.js',import.meta.url),'utf8').replace(/^import.*\n/,'').split('applyPrefs();loadPersonal();render();')[0];
 vm.runInContext(code,context);context.fixture=fixture;vm.runInContext('state.home={trending:[fixture,{...fixture,id:2,title:"Segundo anime"}],recent:[fixture],top:[fixture]};remember(state.home.trending);',context);
 return {context,document,calls,run:s=>vm.runInContext(s,context)};
}
const settle=async()=>{for(let i=0;i<10;i++)await new Promise(resolve=>setImmediate(resolve));};
test('home binds overlay arrows and switches the featured anime',async()=>{const t=setup();await t.run('render()');assert.equal(t.document.querySelectorAll('.catalog-rail .rail-arrow').length,6);assert.equal(t.document.querySelector('.hero h1').textContent,'Anime & teste');t.document.querySelector('[data-hero-step="1"]').onclick();assert.equal(t.document.querySelector('.hero h1').textContent,'Segundo anime');});
test('registration shows full articulated dragon and submits real API request',async()=>{const t=setup();await t.run("location.hash='#cadastro';render()");assert.ok(t.document.querySelector('.living-dragon .dragon-tail'));assert.equal(t.document.querySelectorAll('[data-avatar]').length,12);assert.equal(t.document.querySelector('.auth-dragon'),null);t.document.querySelector('#auth-name').value='Testador';t.document.querySelector('#auth-email').value='test@example.com';t.document.querySelector('#auth-password').value='uma-senha-longa-123';t.document.querySelector('#auth-confirm').value='uma-senha-longa-123';const form=t.document.querySelector('#auth-form');await form.onsubmit({preventDefault(){},currentTarget:form});assert.equal(t.run('state.user.id'),'u1');assert.ok(t.calls.some(x=>x.path==='/api/auth/register'&&x.options.method==='POST'));});
test('details binds episode previews, recommendations and community controls',async()=>{const t=setup();await t.run('openDetails(1)');await settle();assert.ok(t.document.querySelector('.detail-backdrop img'));assert.equal(t.document.querySelectorAll('[data-episode]').length,2);assert.ok(t.document.querySelector('.episode-preview img'));assert.equal(t.document.querySelectorAll('.similar-grid .card').length,1);assert.equal(t.document.querySelectorAll('[data-reaction]').length,2);assert.ok(t.document.querySelector('.comment-login'));});
