const demoKeywordNames=["isekai", "magic", "based on light novel", "romance", "school life", "slice of life", "mecha", "sports", "supernatural", "based on manga", "samurai", "shounen", "science fiction"];
const demoTags=[[0,1,2,11],[9,10,11],[3,12],[1,5,8],[6,12],[3,4,7],[6,11,12],[5,9]];
// Explicit local preview fixtures. Never imported by the production Worker.
const titles=['Crônicas de Aether','Ronin: última aurora','Além das estrelas','O jardim dos espíritos','Cidade de neon','A promessa do oceano','Asas do crepúsculo','Lendas de Kintsugi'];
export const demoItems=titles.map((name,i)=>({id:900001+i,name,title:name,media_type:'tv',genre_ids:[16,10759,10765],demo_keywords:demoTags[i].map(n=>910000+n),origin_country:['JP'],adult:false,overview:[
 'Quando os dragões desaparecem do céu, uma jovem guardiã encontra um ovo de cristal. Para proteger o último sopro de magia, ela precisa atravessar um mundo que esqueceu como sonhar.',
 'Um espadachim sem mestre retorna à cidade onde jurou nunca mais lutar. Entre lanternas e segredos, uma última promessa mudará o destino do império.',
 'Dois desconhecidos recebem a mesma mensagem, enviada por uma estrela que deixou de existir. Uma viagem sobre encontros, distância e tudo o que nos conecta.',
 'Em um jardim onde as estações obedecem às emoções, uma aprendiz descobre que até os espíritos precisam aprender a se despedir.',
 'Nas ruas de uma metrópole que nunca dorme, um entregador encontra uma memória capaz de desligar a cidade inteira.',
 'Uma cartógrafa e um viajante seguem uma canção pelo oceano. No horizonte, uma ilha aparece apenas para quem tem algo a encontrar.',
 'Acima de um mundo coberto por névoa, jovens pilotos defendem a última cidade flutuante e seus sonhos impossíveis.',
 'Uma artesã repara objetos quebrados com ouro. Mas cada peça restaurada revela uma história que alguém tentou esquecer.'
 ][i],poster_path:`/assets/demo/poster-${i+1}.svg`,backdrop_path:`/assets/demo/backdrop-${i+1}.svg`,vote_average:8.9-i*.15,first_air_date:'2026-07-01',genres:[{id:16,name:'Animação'},{id:10765,name:'Fantasia'}],status:'Returning Series',number_of_episodes:12,seasons:[{season_number:1,episode_count:12}],next_episode_to_air:{air_date:new Date(Date.now()+(i+1)*86400000).toISOString().slice(0,10),season_number:1,episode_number:5+i,name:'O próximo horizonte'}}));
export function demoResponse(url){const u=new URL(url),id=Number(u.pathname.match(/\/tv\/(\d+)/)?.[1]);if(u.pathname==='/3/search/keyword'){const name=u.searchParams.get('query'),index=demoKeywordNames.indexOf(name);return Response.json({results:index<0?[]:[{id:910000+index,name}]});}const item=demoItems.find(p=>p.id===id);if(u.pathname.includes('/season/'))return Response.json({episodes:Array.from({length:12},(_,i)=>({episode_number:i+1,season_number:1,name:['O começo da jornada','Um encontro inesperado','Ecos do passado','Do outro lado','A promessa','O céu se abre'][i%6],runtime:24,air_date:'2026-07-01',still_path:item?.backdrop_path}))});if(id&&!u.pathname.endsWith('/recommendations'))return item?Response.json(item):Response.json({}, {status:404});const query=u.searchParams.get('query')?.toLowerCase();return Response.json({page:1,total_pages:1,results:query?demoItems.filter(p=>p.name.toLowerCase().includes(query)):u.searchParams.has('with_keywords')?demoItems.filter(p=>p.demo_keywords.includes(Number(u.searchParams.get('with_keywords')))):demoItems});}
